version: "3.4"

services:
  nginx:
    container_name: "violet-nginx"
    build:
      dockerfile: ./Dockerfile
      context: ./Frontend/docker/nginx
      target: prod
    ports:
      - "81:80"
    volumes:
      - ./Frontend:/app
    depends_on:
      - node
    networks:
      - violet

  node:
    container_name: "violet-node"
    build:
      dockerfile: ./Dockerfile
      context: ./Frontend/docker/node
      target: prod
    volumes:
      - ./Frontend:/app
    networks:
      - violet
    command: /run/install.sh

networks:
  violet:

